# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159b53d40583913f22fe1ccf000bca28faae7d24717ca3777d77603412b9c27532b12947cdac2b08d4c3fc5e833c3d13d053f45f5618f0c582720119e31973a0

test:
  secret_key_base: ace751861f89970754af1221696bd1a1b546de33d1479396353af385dd1c5c1905e4649877fd4bd449d9e1ccc6665e084f5fcd5088a6b0802f6ef6ba3e823c5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
